# Generated by Django 3.2.5 on 2021-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=50)),
                ('E-mail', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Phone Number', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnterMeds',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Medication', models.CharField(max_length=50)),
                ('Dosage', models.IntegerField()),
                ('Number in Store', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('timings', models.CharField(max_length=400)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
